project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - slides/*.qmd
  resources:
    - slides/widgets/**
    - slides/assets/**

website:
  title: "Majal AI Track"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/day1.qmd
        text: Day 1
      - href: slides/day2.qmd
        text: Day 2
      - href: slides/day3.qmd
        text: Day 3
      - href: slides/day4.qmd
        text: Day 4

format:
  html:
    theme: cosmo
    toc: true
